### ISSUE TITLE
Code signing certificate showing revoked

### ISSUE THREAD

**Issue by tcreese** [kenh/keychain-pkcs11#14]
<pre><code>codesign --verify --strict --deep --verbose=4 keychain-pkcs11.dylib<br>
keychain-pkcs11.dylib: CSSMERR_TP_CERT_REVOKED<br>
In architecture: x86_64</code></pre>

**Comment by kenh** [comment]
I'm aware of this issue; unfortunately the organization that held the certificate I used to sign the previous kit with revoked the signing certificate and did not warn me they were going to do that. I am working with my management to get a new one and will release a new installer when I get it.

In the interim you can fix this by removing the current signature and replacing it with an ad-hoc one

```
sudo codesign --remove-signature /usr/local/lib/keychain-pkcs11.dylib
sudo codesign -s - -f /usr/local/lib/keychain-pkcs11.dylib
```

**Comment by mcgrawhill** [comment]
Do you have any projected dates for a new release? Thank you.

**Comment by kenh** [comment]
> Do you have any projected dates for a new release? Thank you.

No. I wish I did, but I do not.

**Comment by kenh** [comment]
Fixed! New release just published that is signed using non-revoked certificates!
