### ISSUE TITLE
 Crash in [@ DERDecodeSeqContentInit] in Firefox

### ISSUE THREAD

**Issue by mozkeeler** [kenh/keychain-pkcs11#7]
Hi, we're seeing some crash reports from Firefox users who have this module loaded. See https://bugzilla.mozilla.org/show_bug.cgi?id=1668593

**Comment by kenh** [comment]
Hi,

So, my first obvious question is .. are they running the latest version of keychain-pkcs11? (latest release is 0.9.5).

Secondly ... you can get a lot of debugging information by running at a terminal window:

`log stream --predicate 'subsystem = "mil.navy.nrl.cmf.pkcs11"' --level debug`

If it was possible to get the output of that crash when that happened, it sure would be helpful.

I can also engage directly with the Firefox users if that would be helpful.

**Comment by mozkeeler** [comment]
Don't know the version. The crash reports say the debug id of the library is `38FF608A11793C96A636230D444BC7070`, which I would think is a hash of some kind, but it's 33 characters long, which doesn't make sense.
As far as I know, we only know about this from automated crash reports, and I don't think there's a way to directly talk to the users affected.

**Comment by kenh** [comment]
Huh.  Do you happen to know WHAT a debug id is?  I don't think I am familiar with it.

Is it possible to get more detailed crash data?  I could create an account on the Mozilla bugzilla if that would help. Also, if there is a guide to understanding the Mozilla crash output?  I'm more of a "run it inside of lldb" kind of guy.  It sure would be interesting to see the stack frame for the call to C_GetTokenInfo or SecCertificateCopySubjectSummary().

I am guessing, from the uptime, that it didn't happen right at startup.  So it could have happened when a new smartcard was inserted, or one was removed. But ... I thought I got all of those cases fixed.

**Comment by mozkeeler** [comment]
I don't know - I asked some people who should know, but I haven't heard back from them yet.
You probably don't need a bugzilla account - that bug is public and the links to the crash reports should also be public.
e.g. https://crash-stats.mozilla.org/report/index/6b9ccdfc-8d61-477b-8e75-845710200930

**Comment by kenh** [comment]
I also put comments on the Mozilla bug, but I confirmed these crashes are all from the 0.9.1 release and I believe this issue has been addressed in 0.9.5.  So I am closing this issue.

**Comment by mozkeeler** [comment]
Thanks for looking into this!
