### ISSUE TITLE
How to use with Brew?

### ISSUE THREAD

**Issue by zhao-li** [kenh/keychain-pkcs11#8]
Thank you for creating this library.

I installed this package outside of `brew`, but `brew` now complains with:

```
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/keychain-pkcs11.dylib
```

I'm wondering if you know of a way to have this package live alongside `brew` and suppressing this warning?

Thanks again 🙏🏻

**Comment by kenh** [comment]
I assume you're getting that from `brew doctor`? Because I'm a homebrew user and I've never noticed that in normal homebrew usage.

I do see at the top of the `brew doctor` output:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
```

It seems like you're just supposed to ignore it.

**Comment by zhaol** [comment]
Ok thank you for confirming that there's no other resolution. Have a great one!

**Comment by zhao-li** [comment]
Thank you for confirming there's no other way. Have a great one 😁
